### PR TITLE
Added GLSL_Instructions_Mac.md and GLSL_Instructions_Plex.md

### PR DESCRIPTION
**Pull request by Tama47**

### CODE REVIEW

**Comment by yooooooLeon** [comment]
您的邮件已收到！谢谢！

**Comment by bloc97** [comment]
Thanks for the installation instructions for Mac and Plex!

**Comment by HamzaM** [comment]
> Thanks for the installation instructions for Mac and Plex!

Has it worked for you ?

**Comment by Tama47** [comment]
> Has it worked for you ?

Works for me, using it on a daily basis.

**Comment by HamzaM** [comment]
> > Has it worked for you ?
> 
> 
> 
> Works for me, using it on a daily basis.

Are you using it for plex? I created the folder and dropped the files but it isn't doing anything

**Comment by Tama47** [comment]
> Are you using it for plex?

Yes, I use Anime4K for both Plex and mpv.

> I created the folder and dropped the files but it isn't doing anything

Are you using [Plex for Mac](https://www.plex.tv/media-server-downloads/#plex-app) client app?

You need to add the input.conf and mpv.conf as well as the shaders folder into `~/Library/Application Support/Plex/`

  - Note: Not the input.conf.md and mpv.conf.md
Screenshot 2023-03-22 at 10 33 35 PM

**Comment by HamzaM** [comment]
Oh I was using the AppStore version that's why i guess it was not working, going to try again

**Comment by HamzaM** [comment]
> > Are you using it for plex?
> 
> Yes, I use Anime4K for both Plex and mpv.
> 
> > I created the folder and dropped the files but it isn't doing anything
> 
> Are you using [Plex for Mac](https://www.plex.tv/media-server-downloads/#plex-app) client app?
> 
> You need to add the input.conf and mpv.conf as well as the shaders folder into `~/Library/Application Support/Plex/`
> 
> * Note: Not the input.conf.md and mpv.conf.md
> 
> Screenshot 2023-03-22 at 10 33 35 PM

Works now, i was using the AppStore version that is why it was not working.

Paying close attention I can see some weird lines appearing but they are pretty faint. It looks like a grid.

CleanShot 2023-03-24 at 18 41 20@2x

Ok they are now gone by removing the first line : 

```
~~profile=gpu-hq~~
gpu-api=vulkan
gpu-context=moltenvk
scale=ewa_lanczossharp
cscale=ewa_lanczossharp

glsl-shaders="~~/shaders/Anime4K_Clamp_Highlights.glsl:~~/shaders/Anime4K_Restore_CNN_M.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_M.glsl:~~/shaders/Anime4K_AutoDownscalePre_x2.glsl:~~/shaders/Anime4K_AutoDownscalePre_x4.glsl:~~/shaders/Anime4K_Upscale_CNN_x2_S.glsl"
```

**Comment by Tama47** [comment]
>gpu-api=vulkan
gpu-context=moltenvk
scale=ewa_lanczossharp
cscale=ewa_lanczossharp

How did you get them to work? I seem to be getting error with them.
Screenshot 2023-03-24 at 5 19 15 PM

> do you believe that can have any impact on the SoC

I have been using this setup on my base M1 Mac mini for almost a year now and haven't encountered any slowdowns or overheating issues so far. Typically, I keep my Mac mini running 24/7, and it has been performing fine. While I have occasionally used the setup on my M2 MacBook Air, I haven't noticed any significant impact aside from slight heating and faster battery draining, but I assume that is due to the fanless design. So, I don't think this will have any adverse effects on the SoC.

**Comment by HamzaM** [comment]
> >gpu-api=vulkan
> 
> gpu-context=moltenvk
> 
> scale=ewa_lanczossharp
> 
> cscale=ewa_lanczossharp
> 
> 
> 
> How did you get them to work? I seem to be getting error with them.
> 
> Screenshot 2023-03-24 at 5 19 15 PM
> 
> 
> 
> > do you believe that can have any impact on the SoC
> 
> 
> 
> I have been using this setup on my base M1 Mac mini for almost a year now and haven't encountered any slowdowns or overheating issues so far. Typically, I keep my Mac mini running 24/7, and it has been performing fine. While I have occasionally used the setup on my M2 MacBook Air, I haven't noticed any significant impact aside from slight heating and faster battery draining, but I assume that is due to the fanless design. So, I don't think this will have any adverse effects on the SoC.

Weird, it just worked for me. But i don't think they are useful to be honest

**Pull request merged**
