### PR TITLE
Add Anime4K-Pytorch

### PR DESCRIPTION
**Pull request by Fannovel16**
https://colab.research.google.com/drive/11xAn4fyAUJPZOjrxwnL2ipl_1DGGegkB
Based on @kato-megumi convert script: https://gist.github.com/kato-megumi/44e52b4cc0e082e94d452a7df04243e0
Support models: ['Upscale_S', 'Upscale_M', 'Upscale_L', 'Upscale_VL', 'Upscale_UL', 'Upscale_Denoise_S', 'Upscale_Denoise_M', 'Upscale_Denoise_L', 'Upscale_Denoise_VL', 'Upscale_Denoise_UL', 'Restore_S', 'Restore_L', 'Restore_VL', 'Restore_UL', 'Restore_Soft_S', 'Restore_Soft_M', 'Restore_Soft_L', 'Restore_Soft_VL', 'Restore_Soft_UL']
This notebook also supports fp16 and TensorRT

### CODE REVIEW

**Comment by Fannovel16** [comment]
Archived 16FPS on Colab T4 btw

**Comment by bloc97** [comment]
LGTM, thanks!

**Comment by bloc97** [comment]
> Archived 16FPS on Colab T4 on Preset A (HQ) btw

Interesting that it would be so low on a Tesla T4 (which is basically a 3060 with more VRAM), I would have expected at least 80FPS+...

**Comment by Fannovel16** [comment]
> Interesting that it would be so low on a Tesla T4 (which is basically a 3060 with more VRAM), I would have expected at least 80FPS+...

That is only 720p with batch size 1. Idk if MPV/libplacebo processes frame-by-frame or does batch processing.

**Pull request merged**
