### PR TITLE
Automatic shaders installer for Windows

### PR DESCRIPTION
**Pull request by dvdvideo1234**

### CODE REVIEW

**Comment by dvdvideo1234** [comment]
The user must install [`Git`](https://git-scm.com/) before running the script.

**Review by MoonLGH — APPROVED** [review]
i approve though, but here is the thing, what if someone didnt want `echo scale=ewa_lanczossharp >> mpv.conf` ?
they had to edit the input.conf ?

**Comment by dvdvideo1234** [comment]
Yep, or you can add option for `Enable feature X [y/N] ?` for every of these features. Values different than `Y` or `y` are evaluated to `N` ;) I do not know which features are complementary though. I only made it from the documentation..

**Comment by hooke007** [comment]
It could be an alt choice only for those who don't understand the `Usage Instructions` and never got in touch with mpv.
But not necessary to be included in this repo, could be another individual repo.

**Comment by dvdvideo1234** [comment]
@hooke007 

Simply I would not care less. Do whatever you like. I tough it would help you out at the time ;)

**Comment by mhtvsSFrpHdE** [comment]
@dvdvideo1234 

Depending on git is not a good idea, especially your users are not everyone programmer  
to install a 99% not in use software.  
As alternative, curl/wget, powershell built-in download method and HTTP proxy support is an option.  
Your user can spread all over the world, at location like [] or [].  
They use proxy server to access github.

I will prefer a standalone download package so I could use it completely offline.

For activate Anime4K, I suggest my lua script instead of input.conf  
https://github.com/mhtvsSFrpHdE/AnimeAnyK-mpv

Do not modify mpv.conf by default, turn them into optional checkbox.  
You can break a configured mpv instance easily by writing random things.

**Comment by dvdvideo1234** [comment]
@mhtvsSFrpHdE

I would not relay on `wget` or `curl`, because thay are not native `NT` applications and you are to be relaying the user to have these prior. The fix for the problem must not be `Please install Windows 10` because this is not a fix ;)
```
C:\Users\DVD>curl --version
'curl' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\DVD>wget --version
'wget' is not recognized as an internal or external command,
operable program or batch file.
```

Whatever you decide to do will probably better so god speed!

**Comment by mhtvsSFrpHdE** [comment]
> @mhtvsSFrpHdE
> 
> Sorry for closing this without an answer...
> 
> I would not use `wget` or `curl`, because thay are not native `NT` applications and you are to be relaying the user to have these prior. The fix for the problem must not be [`Please install Windows 10`](https://superuser.com/questions/25538/how-to-download-files-from-command-line-in-windows-like-wget-or-curl) because this is not a fix ;)
> 
> ```
> C:\Users\DVD>curl --version
> 'curl' is not recognized as an internal or external command,
> operable program or batch file.
> 
> C:\Users\DVD>wget --version
> 'wget' is not recognized as an internal or external command,
> operable program or batch file.
> ```
> 
> Whatever you decide to do will probably better so god speed!

You have `git clone https://github.com/bloc97/Anime4K.git %confDIR%` command and  
> Depending on git is not a good idea

Windows does not recognize git if you don't install git.  
When we are talking about Windows, the Windows way to install things is `*.exe` and several `*.dll`,  
or a whole big `*.exe` self-extract everything to temp after launch.  
An online installer example is Qt official installer, an offline example is GIMP installer.

The `*.bat` problem is you can do very limited things with pure Windows command line environment.  
For example, you can't unzip `*.rar` and `*.7z` without install 3rd party software. Git too.

Draw a GUI on Windows also expensive, soon you'll discover you need an installer of your installer  
to make sure the installer can run...  
or do things like putting vc_redist 2005 on a 2022 computer,  
or a API is work on 10 and XP and Vista but not 7

Anyway I'm good to see people can do project surrounding, automatic works  
It's a shame, all of my project still come without a Windows installer for these reasons.

**Pull request closed without merging**
